#       ----------- + AdminGUI by Ziga Zajc + -----------   #
#                                                           #
#                            Config                         #
#                                                           #
#       --------- + ------------------------- + ---------   #
#
#       You can use chat colors:
#                ________________________
#               |   code: | color:       |
#               |________________________|
#               |     &0  |	Black	     |
#               |     &1  |	Dark Blue	 |
#               |     &2  |	Dark Green	 |
#               |     &3  |	Dark Aqua	 |
#               |     &4  |	Dark Red	 |
#               |     &5  |	Dark Purple	 |
#               |     &6  |	Gold	     |
#               |     &7  |	Gray	     |
#               |     &8  |	Dark Gray	 |
#               |     &9  |	Blue	     |
#               |     &a  |	Green	     |
#               |     &b  |	Aqua	     |
#               |     &c  |	Red	         |
#               |     &d  |	Light Purple |
#               |     &e  |	Yellow	     |
#               |     &f  |	White	     |
#               |     &k  |	Obfuscated	 |
#               |     &l  |	Bold	     |
#               |     &m  |	Strikethrough|
#               |     &n  |	Underline	 |
#               |     &o  |	Italic	     |
#               |     &r  |	Reset	     |
#               |________________________|
#
#----------------------------------------------------------
#                       Admin GUI
#----------------------------------------------------------
# If gui_type is set to 0, then Minecraft items will be used in gui (faster).
# If gui_type is set to 1, then Player heads will be used in gui (slower but nicer).
gui_type: 0
# If initialize_gui is set to 0 then gui won't be initialized and will be very buggy on first use. (You will be still able to initialize the gui in game with /admin initialize gui)
# If initialize_gui is set to 1 then gui will be initialized when player join the game. (Recommended if you have gui_type set to 1)
initialize_gui: 0
# How many seconds expires before next player head will start initializing. (Default is 2) (Lower number is faster but more buggier)
initialize_delay: 2
# If initialize_reminder is set to true then players will be reminded when GUI will start initializing and when it will finish. Only use on versions 1.14.x+ (Default is false)
initialize_reminder: false
# Players will see messages in default language (Default is English) - Available options: English, Bulgarian, Chinese, Dutch, Finnish, French, German, Hebrew, Italian, Japanese, Korean, Latvian, Portuguese, Russian, Slovak, Spanish, Swedish and Turkish.
# If you translate plugin into any other language feel free to send it and I will include it into this plugin.
default_language: "English"
# Here you can specify default GUI color - Only works with stained glass panes.
gui_default_color: "LIGHT_BLUE_STAINED_GLASS_PANE"
# How would you like to display date in Admin GUI plugin? (y = year, M = month, d = day, H = hour, m = minute and s = second)
date_format: "yyyy-MM-dd HH:mm:ss"
# Do you want to show player IP addresses in Admin GUI?
show_ips: true
#----------------------------------------------------------
#                     Update Checker
#----------------------------------------------------------
# Do you want update checker to be enabled?
uc_enabled: true
uc_notify: "&aNew update is available. Please update me to &b{version}&a."
# if uc_send_type is set to 0 then only console will be notified when update is available.
# if uc_send_type is set to 1 then console and players with admingui.admin permission will be notified when update is available. (Default and recommended)
uc_send_type: 1
#----------------------------------------------------------
#             Custom Join / Leave message
#----------------------------------------------------------
# Do you want custom join / leave message to be enabled?
cjlm_enabled: false
# Here you can set your own join message format for all new players (Valid tags are {name} and {display_name}) or null for no first join message
first_join_message: "&7[&1+&7] &6{display_name}"
# Here you can set your own join message format (Valid tags are {name} and {display_name}) or null for no join message
join_message: "&7[&a+&7] &6{display_name}"
# Here you can set your own leave message format (Valid tags are {name} and {display_name}) or null for no leave message
leave_message: "&7[&4-&7] &6{display_name}"
#----------------------------------------------------------
#                   Custom MOTD changer
#----------------------------------------------------------
# Do you want custom MOTD changer to be enabled?
motd_changer_enabled: false
# Here you can set the message that will be displayed in MOTD.
motd_changer_motd: "&6&lWelcome to my server"
# Here you can change max players.
motd_changer_max_players: 100
#----------------------------------------------------------
#                   Command disabler
#----------------------------------------------------------
# Do you want command disabled to be enabled?
command_disabler_enabled: false
# On the left side are disabled commands and on the right side messages that will be displayed if player tried to execute that command.
disabled_commands:
  "/ver" : "&cBecause of security risk, we have disabled this command."
  "/bukkit:ver" : "&cBecause of security risk, we have disabled this command."
  "/version" : "&cBecause of security risk, we have disabled this command."
  "/bukkit:version" : "&cBecause of security risk, we have disabled this command."
  "/about" : "&cBecause of security risk, we have disabled this command."
  "/bukkit:about" : "&cBecause of security risk, we have disabled this command."
  "/icanhasbukkit" : "&cBecause of security risk, we have disabled this command."
  "/help" : "&cBecause of security risk, we have disabled this command."
  "/minecraft:help" : "&cBecause of security risk, we have disabled this command."
  "/bukkit:help" : "&cBecause of security risk, we have disabled this command."
  "/me" : "&cBecause of security risk, we have disabled this command."
  "/minecraft:me" : "&cBecause of security risk, we have disabled this command."
  "/bukkit:?" : "&cBecause of security risk, we have disabled this command."
  "/plugins" : "&cBecause of security risk, we have disabled this command."
  "/bukkit:plugins" : "&cBecause of security risk, we have disabled this command."
  "/pl" : "&cBecause of security risk, we have disabled this command."
  "/bukkit:pl" : "&cBecause of security risk, we have disabled this command."
#----------------------------------------------------------
#          Random teleport command (/rtp, /wild)
#----------------------------------------------------------
# Do you want Random teleport command to be enabled?
rtp_enabled: false
# Teleport between x coordinates. (Make sure that min value is always smaller then max)
rtp_min_x: -1000
rtp_max_x: 1000
# Teleport between z coordinates. (Make sure that min value is always smaller then max)
rtp_min_z: -1000
rtp_max_z: 1000
# How many times do you want RTP to try find safe location? After this amount of attempts RTP will stop searching for safe location.
rtp_attempts: 20
# How many seconds does player needs to wait before it can execute rtp command again.
rtp_delay: 10
# This message will be send when player don't wait for delay.
rtp_delay_message: "&cYou need to wait {seconds} seconds, before you can execute /rtp command again!"
# This message will be send when player execute /rtp or /wild command.
rtp_begin: "&aFinding safe location..."
# This message will be send to player after they teleport successfully.
rtp_success: "&aYou have been teleported to safe location."
# This message will be send if safe location can't be found in certain amount of attempts.
rtp_failed: "&cSafe location to teleport can't be found. Please try again later."
#----------------------------------------------------------
#                      Admin Tools
#----------------------------------------------------------
admin_tools_enabled: true
admin_tools_name: "&c&lAdmin Tools"
admin_tools_material: "NETHER_STAR"
admin_tools_enchantment: false
admin_tools_lore: "&dClick me to open Admin GUI"
# Do you want to give Admin Tools to players with admingui.admin permission when they join?
admin_tools_give_on_join: false
# On which slot do you want to give Admin Tools? (Note that if player already have something in this slot it will be deleted)
admin_tools_give_on_join_slot: 0
#----------------------------------------------------------
#                   Admin Permissions
#----------------------------------------------------------
# Do you want Admin Permissions to be enabled?
ap_enabled: false
# Were and how do you want to save ranks?
# if ap_storage_type is set to 0, then ranks will be saved into permissions.yml file
# if ap_storage_type is set to 1, then ranks will be synchronized through Bungeecord servers (Make sure that Bungeecord is enabled)
# if ap_storage_type is set to 2, then ranks will be saved into MySql database (Make sure that MySQL is enabled and connected properly)
ap_storage_type: 0
#----------------------------------------------------------
#            Admin Chat - Support PlaceholderAPI
#----------------------------------------------------------
# Do you want Admin Staff Chat to be enabled?
ac_enabled: false
# Here you can set your own Admin Chat format (Valid tags are {name}, {display_name}, {message} and {server_name})
# If you have enabled Admin Permissions then you can use tags {prefix} and {suffix} to display player rank.
# If you don't use Admin Permissions as your permission manager then you can use tags {vault_prefix} and {vault_suffix}
ac_format: "{vault_prefix} &7{display_name} &7> {message}"
# Here you can specify default Chat color - Available options: WHITE_WOOL, ORANGE_WOOL, MAGENTA_WOOL, LIGHT_BLUE_WOOL, YELLOW_WOOL, LIME_WOOL, PINK_WOOL, GRAY_WOOL, LIGHT_GRAY_WOOL, CYAN_WOOL, PURPLE_WOOL, BLUE_WOOL, GREEN_WOOL, RED_WOOL, BLACK_WOOL, CLOCK, EXPERIENCE_BOTTLE (1.16+)
# You can also use NONE for
ac_default_color: "LIGHT_GRAY_WOOL"
# If beautifier is enabled, every message will start with uppercase and end with dot.
ac_beautifier: true
# How many seconds, player needs to wait until the next message can be sent?
ac_delay: 0
# What will be sent to players if they start spamming in chat?
ac_delay_message: "&cYou need to wait {seconds} seconds to sent another message!"
# Which prefix will be used for determining css colors.
ac_color_prefix: ";"
# Here words on the left will be replaced with words on the right.
ac_emojis:
  ":)" : "☺"
  ":(" : "☹"
  "<3" : "&4❤&7"
  "ugly" : "cute"
# Which bad words should be blocked in chat?
ac_filter:
  - "fuck"
  - "shit"
  - "pussy"
  - "dick"
  - "nigger"
  - "cock"
  - "bitch"
#----------------------------------------------------------
#         Admin Tablist - Support PlaceholderAPI
#----------------------------------------------------------
# Do you want Admin Tablist to be enabled?
atl_enabled: false
# If you want to show how many players are online in Tablist we would need to refresh it for every player, every time someone join or leave the server.
# So if you won't use {online_players} tag in formats below leave it to false
atl_show_online_players: false
# Here you can set your own Admin Tablist formats (Valid tags are {name}, {display_name}, {online_players} <- (require atl_show_online_players to be true))
# If you have enabled Admin Permissions you can use {prefix} and {suffix} tag to display players rank.
# If you don't use Admin Permissions as your permission manager then you can use tags {vault_prefix} and {vault_suffix}
atl_header: "\n &6&lWelcome &c&l{display_name} &6&lto my server! \n"
atl_format: "{vault_prefix} &7{display_name}"
atl_footer: "\n&cChange me in config.yml file!"
#----------------------------------------------------------
#                   Multiplayer Sleep
#----------------------------------------------------------
# Do you want Multiplayer Sleep to be enabled?
ms_enabled: false
# How many percentages of players do you want to sleep for the night to be skipped?
ms_percentages: 50
# What message do you want to show when someone goes to bed? (Valid tags are {name}, {display_name}, {until_skip}, {online_players}) (If you don't want to show any message set it to null)
ms_message: "&9{display_name} went to sleep. Only {until_skip} more players needs to go to sleep for the night to be skipped."
#----------------------------------------------------------
#         Admin Command Spy - Support PlaceholderAPI
#----------------------------------------------------------
# Do you want Admin Command Spy to be enabled?
acs_enabled: false
# Here you can set your own Admin Command Spy format (Valid tags are {name}, {display_name} and {message})
acs_format: "&7[Command Spy] {name} &7> {message}"
# Admin Command Spy will ignore those commands
acs_ignore:
  - "/login"
  - "/register"
#----------------------------------------------------------
#         Custom Chat Channels - Support PlaceholderAPI
#----------------------------------------------------------
# Here you can create custom chat channels.
ccc:
  staffchat:
    name: "Staff Chat"
    format: "&2[&cStaff Chat&2] &5{name} &f> {message}"
    permission: "admingui.chat.staff"
    aliases:
      - "sc"
      - "schat"
  devchat:
    name: "Dev Chat"
    format: "&2[&6Dev Chat&2] &5{name} &f> {message}"
    permission: "admingui.chat.dev"
    aliases:
      - "dc"
      - "dchat"
  vip++chat:
    name: "Vip++ Chat"
    format: "&2[&3Vip++ Chat&2] &5{name} &f> {message}"
    permission: "admingui.chat.vip++"
    aliases:
      - "vc++"
      - "vchat++"
      - "vipchat++"
#----------------------------------------------------------
#                   Freeze Settings
#----------------------------------------------------------
# Decide what players can't do when they are frozen. (true = can't do and false = can do)
freeze_player_move: true
freeze_move_inventory: true
freeze_execute_commands: true
freeze_send_message: true
freeze_break_blocks: true
freeze_place_block: true
freeze_drop_items: true
# In which channel player will be able to chat when it will be frozen
freeze_admin_chat: "staffchat"
# Do you want to display frozen player title and subtitle? If not set it to null
freeze_title: "&bYou are frozen!"
freeze_subtitle: "&cPlease listen to staff!"
#----------------------------------------------------------
#                       Bungeecord
#----------------------------------------------------------
# If you enable bungeecord you will have control over other players on other servers.
bungeecord_enabled: false
# You can write what ever you want in server_name, but 2 servers can't have the same name. (I suggest the same names as in bungeecord config file)
server_name: "Lobby"
# If bungeecord Admin Chat is enabled, messages will be send on every server that is connected to bungeecord and has this feature enabled. (Require AdminGUIBungee)
bungeecord_admin_chat: false
# Here you can set your own Bungeecord Admin Chat format (Valid tags are {name}, {display_name}, {message} and {server_name})
# If you have enabled Admin Permissions then you can use tags {prefix} and {suffix} to display player rank.
# If you don't use Admin Permissions as your permission manager then you can use tags {vault_prefix} and {vault_suffix}
bungeecord_admin_chat_format: "&7[{server_name}] &7{display_name} &7> {message}"
# If control_type is set to 0, then you will be teleported on the same server as target player is located.
# If control_type is set to 1, then you can control player even tho you aren't on the same server as target player is. (Coming soon...)
control_type: 0
#----------------------------------------------------------
#                   Database - MySQL
#----------------------------------------------------------
# Do you want to enable mysql database?
mysql: false
# Here are all data for connection to Mysql database. Please create database, user and password by yourself. Do not use root as user, because of security risk!
mysql_host: "localhost"
mysql_port: "3306"
mysql_database: "AdminGUI"
mysql_user: "root"
mysql_password: ""
mysql_useSSL: false