#       ----------- + AdminGUI by Ziga Zajc + -----------   #
#                                                           #
#                            Config                         #
#                                                           #
#       --------- + ------------------------- + ---------   #
#
#       You can use chat colors:
#                ________________________
#               |   code: | color:       |
#               |________________________|
#               |     &0  |	Black	     |
#               |     &1  |	Dark Blue	 |
#               |     &2  |	Dark Green	 |
#               |     &3  |	Dark Aqua	 |
#               |     &4  |	Dark Red	 |
#               |     &5  |	Dark Purple	 |
#               |     &6  |	Gold	     |
#               |     &7  |	Gray	     |
#               |     &8  |	Dark Gray	 |
#               |     &9  |	Blue	     |
#               |     &a  |	Green	     |
#               |     &b  |	Aqua	     |
#               |     &c  |	Red	         |
#               |     &d  |	Light Purple |
#               |     &e  |	Yellow	     |
#               |     &f  |	White	     |
#               |     &k  |	Obfuscated	 |
#               |     &l  |	Bold	     |
#               |     &m  |	Strikethrough|
#               |     &n  |	Underline	 |
#               |     &o  |	Italic	     |
#               |     &r  |	Reset	     |
#               |________________________|
#
#----------------------------------------------------------
#                       Admin GUI
#----------------------------------------------------------
# If gui_type is set to 0, then Minecraft items will be used in gui (faster).
# If gui_type is set to 1, then Player heads will be used in gui (slower but nicer).
gui_type: 0
# If initialize_gui is set to 0 then gui won't be initialized and will be very buggy on first use. (You will be still able to initialize the gui in game with /admin initialize gui)
# If initialize_gui is set to 1 then gui will be initialized when player join the game. (Recommended if you have gui_type set to 1)
initialize_gui: 0
# How many seconds expires before next player head will start initializing. (Default is 2) (Lower number is faster but more buggier)
initialize_delay: 2
# If initialize_reminder is set to true then players will be reminded when GUI will start initializing and when it will finish. Only use on versions 1.14.x+ (Default is false)
initialize_reminder: false
# Players will see messages in default language (Default is English) - Available options: English, Chinese, French, Spanish, Russian, Italian, Dutch, Dutch, Hebrew, Korean, Slovak, Swedish, Bulgarian, Turkish and Portuguese.
# If you translate plugin into any other language feel free to send it and I will include it into this plugin.
default_language: "English"
# Here you can specify default GUI color - Only works with stained glass panes.
gui_default_color: "LIGHT_BLUE_STAINED_GLASS_PANE"
# How would you like to display date in Admin GUI plugin? (y = year, M = month, d = day, H = hour, m = minute and s = second)
date_format: "yyyy-MM-dd HH:mm:ss"
#----------------------------------------------------------
#                     Update Checker
#----------------------------------------------------------
# Do you want update checker to be enabled?
uc_enabled: true
uc_notify: "&aNew update is available. Please update me to &b{version}&a."
# if uc_send_type is set to 0 then only console will be notified when update is available.
# if uc_send_type is set to 1 then console and players with admingui.admin permission will be notified when update is available. (Default and recommended)
uc_send_type: 1
#----------------------------------------------------------
#                       Admin Tools
#----------------------------------------------------------
admin_tools_enabled: true
admin_tools_name: "&c&lAdmin Tools"
admin_tools_material: "NETHER_STAR"
admin_tools_enchantment: false
admin_tools_lore: "&dClick me to open Admin GUI"
#----------------------------------------------------------
#                    Admin Permissions
#----------------------------------------------------------
# Do you want Admin Permissions to be enabled?
ap_enabled: false
# Were and how do you want to save ranks?
# if ap_storage_type is set to 0, then ranks will be saved into permissions.yml file
# if ap_storage_type is set to 1, then ranks will be synchronized through Bungeecord servers (Make sure that Bungeecord is enabled)
# if ap_storage_type is set to 2, then ranks will be saved into MySql database (Make sure that MySQL is enabled and connected properly)
ap_storage_type: 0
#----------------------------------------------------------
#            Admin Chat - Support PlaceholderAPI
#----------------------------------------------------------
# Do you want Admin Staff Chat to be enabled?
ac_enabled: false
# Here you can set your own Admin Chat format (Valid tags are {name}, {display_name}, {message} and {server_name})
# If you have enabled Admin Permissions then you can use tags {prefix} and {suffix} to display player rank.
# If you don't use Admin Permissions as your permission manager then you can use tags {vault_prefix} and {vault_suffix}
ac_format: "&7{display_name} &7> {message}"
# If beautifier is enabled, every message will start with uppercase and end with dot.
ac_beautifier: true
# How many seconds, player needs to wait until the next message can be sent?
ac_delay: 0
# What will be sent to players if they start spamming in chat?
ac_delay_message: "&cYou need to wait {seconds} seconds to sent another message!"
# Which prefix will be used for determining css colors.
ac_color_prefix: ";"
# Which bad words should be blocked in chat?
ac_filter:
  - "fuck"
  - "shit"
  - "pussy"
  - "dick"
  - "nigger"
  - "cock"
  - "bitch"
#----------------------------------------------------------
#         Admin Tablist - Support PlaceholderAPI
#----------------------------------------------------------
# Do you want Admin Tablist to be enabled?
atl_enabled: false
# Here you can set your own Admin Tablist formats (Valid tags are {name} and {display_name})
# If you have enabled Admin Permissions you can use {prefix} and {suffix} tag to display players rank.
# If you don't use Admin Permissions as your permission manager then you can use tags {vault_prefix} and {vault_suffix}
atl_header: "\n &6&lWelcome &c&l{display_name} &6&lto my server! \n"
atl_format: "&a{display_name}"
atl_footer: "\n&cChange me in config.yml file!"
#----------------------------------------------------------
#         Admin Command Spy - Support PlaceholderAPI
#----------------------------------------------------------
# Do you want Admin Command Spy to be enabled?
acs_enabled: false
# Here you can set your own Admin Command Spy format (Valid tags are {name}, {display_name} and {message})
acs_format: "&7[Command Spy] {name} &7> {message}"
# Admin Command Spy will ignore those commands
acs_ignore:
  - "/login"
  - "/register"
#----------------------------------------------------------
#         Custom Chat Channels - Support PlaceholderAPI
#----------------------------------------------------------
# Here you can create custom chat channels.
ccc:
  staffchat:
    name: "Staff Chat"
    format: "&2[&cStaff Chat&2] &5{name} &f> {message}"
    permission: "admingui.chat.staff"
    aliases:
      - "sc"
      - "schat"
  devchat:
    name: "Dev Chat"
    format: "&2[&6Dev Chat&2] &5{name} &f> {message}"
    permission: "admingui.chat.dev"
    aliases:
      - "dc"
      - "dchat"
  vip++chat:
    name: "Vip++ Chat"
    format: "&2[&3Vip++ Chat&2] &5{name} &f> {message}"
    permission: "admingui.chat.vip++"
    aliases:
      - "vc++"
      - "vchat++"
      - "vipchat++"
#----------------------------------------------------------
#                   Freeze Settings
#----------------------------------------------------------
# Decide what players can't do when they are frozen. (true = can't do and false = can do)
freeze_player_move: true
freeze_move_inventory: true
freeze_execute_commands: true
freeze_send_message: true
freeze_break_blocks: true
freeze_place_block: true
freeze_drop_items: true
# In which channel player will be able to chat when it will be frozen
freeze_admin_chat: "staffchat"
#----------------------------------------------------------
#                       Bungeecord
#----------------------------------------------------------
# If you enable bungeecord you will have control over other players on other servers.
bungeecord_enabled: false
# You can write what ever you want in server_name, but 2 servers can't have the same name. (I suggest the same names as in bungeecord config file)
server_name: "Lobby"
# If bungeecord Admin Chat is enabled, messages will be send on every server that is connected to bungeecord and has this feature enabled. (Require AdminGUIBungee)
bungeecord_admin_chat: false
# Here you can set your own Bungeecord Admin Chat format (Valid tags are {name}, {display_name}, {message} and {server_name})
# If you have enabled Admin Permissions then you can use tags {prefix} and {suffix} to display player rank.
# If you don't use Admin Permissions as your permission manager then you can use tags {vault_prefix} and {vault_suffix}
bungeecord_admin_chat_format: "&7[{server_name}] &7{display_name} &7> {message}"
# If control_type is set to 0, then you will be teleported on the same server as target player is located.
# If control_type is set to 1, then you can control player even tho you aren't on the same server as target player is. (Coming soon...)
control_type: 0
#----------------------------------------------------------
#                   Database - MySQL
#----------------------------------------------------------
# Do you want to enable mysql database?
mysql: false
# Here are all data for connection to Mysql database. Please create database, user and password by yourself. Do not use root as user, because of security risk!
mysql_host: "localhost"
mysql_port: "3306"
mysql_database: "AdminGUI"
mysql_user: "root"
mysql_password: ""
mysql_useSSL: false