#       ----------- + AdminGUI by Ziga Zajc + -----------   #
#                                                           #
#                           Settings                        #
#                                                           #
#       --------- + ------------------------- + ---------   #