name: AdminGUI-Premium
version: 3.0.1
main: com.rabbitcompany.admingui.AdminGUI
api-version: 1.13
authors: [RabbitCompany]
description: Easy manage your Minecraft server with Admin GUI
softdepend: [Vault, SuperVanish, PremiumVanish, LiteBans, AdvancedBan]
commands:
  admin:
    usage: /<command>
    description: Show Admin GUI
