name: AdminGUI-Premium
version: 5.7.1
main: com.rabbitcompany.admingui.AdminGUI
api-version: 1.13
authors: [RabbitCompany]
description: Easy manage your Minecraft server with Admin GUI
website: rabbit-company.com
softdepend: [Vault, SuperVanish, PremiumVanish, LiteBans, AdvancedBan, AdminBans, PlaceholderAPI, DiscordSRV]
commands:
  admin:
    usage: /<command>
    description: Show Admin GUI
  adminchat:
    usage: /<command>
    description: Manage with Admin Chat
    aliases: [achat, ac]
  admincommandspy:
    usage: /<command>
    description: Spy on players commands
    aliases: [acommandspy, admincs, acs]
permissions:
  admingui.admin:
    description: Grants access to open Admin GUI
    default: op
  admingui.heal:
    description: Grants access to heal yourself
    default: op
  admingui.feed:
    description: Grants access to feed yourself
    default: op
  admingui.gamemode:
    description: Grants access to manage with gamemodes
    default: op
  admingui.gamemode.survival:
    description: Grants access to manage with gamemodes
    default: op
  admingui.gamemode.creative:
    description: Grants access to manage with gamemodes
    default: op
  admingui.gamemode.adventure:
    description: Grants access to manage with gamemodes
    default: op
  admingui.gamemode.spectator:
    description: Grants access to manage with gamemodes
    default: op
  admingui.god:
    description: Grants access to toggle god mode
    default: op
  admingui.potions:
    description: Grants access to manage with potions
    default: op
  admingui.spawner:
    description: Grants access to manage with spawners
    default: op
  admingui.kill:
    description: Grants access to kill yourself
    default: op
  admingui.burn:
    description: Grants access to burn yourself
    default: op
  admingui.time:
    description: Grants access to change time
    default: op
  admingui.weather:
    description: Grants access to change weather
    default: op
  admingui.info:
    description: Grants access to see players info
    default: op
  admingui.spawner.other:
    description: Grants access to spawn mobs on other players
    default: op
  admingui.kick.other:
    description: Grants access to kick other players
    default: op
  admingui.kick.bypass:
    description: Become immune to kicks
    default: op
  admingui.ban:
    description: Grants access to ban players
    default: op
  admingui.ban.bypass:
    description: Become immune to bans
    default: op
  admingui.mute:
    description: Grants access to mute other players
    default: op
  admingui.unmute:
    description: Grants access to unmute other players
    default: op
  admingui.unban:
    description: Grants access to unban other players
    default: op
  admingui.heal.other:
    description: Grants access to heal other players
    default: op
  admingui.feed.other:
    description: Grants access to feed other players
    default: op
  admingui.gamemode.other:
    description: Grants access to change gamemode for other players
    default: op
  admingui.gamemode.other.survival:
    description: Grants access to change gamemode for other players
    default: op
  admingui.gamemode.other.creative:
    description: Grants access to change gamemode for other players
    default: op
  admingui.gamemode.other.adventure:
    description: Grants access to change gamemode for other players
    default: op
  admingui.gamemode.other.spectator:
    description: Grants access to change gamemode for other players
    default: op
  admingui.god.other:
    description: Grants access to give god mode to other players
    default: op
  admingui.teleport:
    description: Grants access to teleport to other players
    default: op
  admingui.potions.other:
    description: Grants access to give potion effects to other players
    default: op
  admingui.kill.other:
    description: Grants access to kill other players
    default: op
  admingui.burn.other:
    description: Grants access to burn other players
    default: op
  admingui.teleport.other:
    description: Grants access to teleport other player to you
    default: op
  admingui.money:
    description: Grants access to manage with your money
    default: op
  admingui.money.other:
    description: Grants access to manage others money
    default: op
  admingui.inventory:
    description: Grants access to see players inventory
    default: op
  admingui.inventory.edit:
    description: Grants access to edit players inventory
    default: op
  admingui.enderchest:
    description: Grants access to see players enderchest
    default: op
  admingui.enderchest.edit:
    description: Grants access to edit players enderchest
    default: op
  admingui.vanish:
    description: Grants access to toggle vanish
    default: op
  admingui.vanish.other:
    description: Grants access to vanish other players
    default: op
  admingui.firework:
    description: Grants access to spawn firework
    default: op
  admingui.firework.other:
    description: Grants access to spawn firework on other player
    default: op
  admingui.lightning:
    description: Grants access to spawn lightning
    default: op
  admingui.lightning.other:
    description: Grants access to spawn lightning on other player
    default: op
  admingui.fakeop:
    description: Grants access fake op other player
    default: op
  admingui.custom:
    description: Grants access to custom commands
    default: op
  admingui.freeze.other:
    description: Grants access to freeze other player
    default: op
  admingui.freeze.bypass:
    description: Become immune to freeze
    default: op
  admingui.rtp.delay.bypass:
    description: Bypass rtp delay
    default: op
  admingui.maintenance:
    description: Bypass maintenance mode
    default: op
  admingui.maintenance.manage:
    description: Grants access to toggle maintenance mode
    default: op
  admingui.reload:
    description: Grants access to reload all configuration files
    default: op
  admingui.chat.staff:
    description: Grants access to read and write messages in Admin Staff chat
    default: op
  admingui.chat.color:
    description: Grants access to write colorful messages
    default: op
  admingui.chat.filter.bypass:
    description: Bypass bad words
    default: op
  admingui.chat.advertisement.bypass:
    description: Grants access for players to send links in chat
    default: op
  admingui.chat.clear:
    description: Grants access to clear the chat
    default: op
  admingui.chat.mute:
    description: Grants access to mute chat
    default: op
  admingui.chat.mute.bypass:
    description: Bypass muted chat
    default: op
  admingui.chat.delay.bypass:
    description: Bypass chat delay
    default: op
  admingui.chat.spy:
    description: Grants access to spy on other players
    default: op
  admingui.chat.color.change:
    description: Grants access to change your default chat color
    default: op
  admingui.chat.color.change.other:
    description: Grants access to change ydefault chat color for others
    default: op
  admingui.rank.set:
    description: Grants access to set players rank
    default: op
  admingui.rank.up:
    description: Grants access to rank up a player
    default: op
  admingui.rank.down:
    description: Grants access to rank down a player
    default: op
  admingui.check:
    description: Grants access to check players stats
    default: op