name: AdminGUI-Premium
version: 4.0.0
main: com.rabbitcompany.admingui.AdminGUI
api-version: 1.13
authors: [RabbitCompany]
description: Easy manage your Minecraft server with Admin GUI
softdepend: [Vault, SuperVanish, PremiumVanish, LiteBans, AdvancedBan, PlaceholderAPI]
commands:
  admin:
    usage: /<command>
    description: Show Admin GUI
  ban:
    usage: /<command>
    description: Ban player
  unban:
    usage: /<command>
    description: Unban player