name: AdminGUI-Premium
version: 5.0.4
main: com.rabbitcompany.admingui.AdminGUI
api-version: 1.13
authors: [RabbitCompany]
description: Easy manage your Minecraft server with Admin GUI
website: rabbit-company.com
softdepend: [Vault, SuperVanish, PremiumVanish, LiteBans, AdvancedBan, AdminBans, PlaceholderAPI]
commands:
  admin:
    usage: /<command>
    description: Show Admin GUI
  #adminchat:
    #usage: /<command>
    #description: Communicate with staffs only
    #aliases: [achat, ac]
  admincommandspy:
    usage: /<command>
    description: Spy on players commands
    aliases: [acommandspy, admincs, acs]